services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Relative to context
    ports:
      - "5000:5000"
    container_name: frontend-container
  
  # node-app:
  #   build:
  #     context: ./backend 
  #     dockerfile: Dockerfile # Relative to context
  #   ports:
  #     - "3000:3000"
  #   container_name: backend-container 