services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile # Relative to context
    ports:
      - "5000:5000"
    container_name: web-app
    env_file: 
      - "../myenv.env"
    volumes:
      - /app/frontend/node_modules
      - ./:/app/frontend
  
  # node-app:
  #   build:
  #     context: ./backend 
  #     dockerfile: Dockerfile # Relative to context
  #   ports:
  #     - "3000:3000"
  #   container_name: backend-container 